### ISSUE TITLE
Program terminates when adding episodes to the queue

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#112]
I added a new series (https://www.crunchyroll.com/series/GYX08020R/knights--magic), but the program just terminates abruptly. Refreshing episodes appears to work, but the crash occurs after I click on "Add to Queue". There is a long pause before the program just terminates. As far as I can tell, no downloads actually start.

The only thing in the log file is:

Error: System.Net.Http.HttpRequestException: Response status code does not indicate success: 420.
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CRD.Utils.HttpClientReq.SendHttpRequest(HttpRequestMessage request) 
 Response: {"error":"TOO_MANY_ACTIVE_STREAMS"}

I am running the latest code, released today (1.5.27)

**Comment by petenun** [comment]
I realized that this happened after I set max simultaneous downloads to 6. I set it down to 4, and everything works without crashing. I wonder if CrunchyRoll can only handle so many streams being pulled at the same time.

**Comment by Elwador** [comment]
hm maybe it depends on your subscription - i just tried 6 episodes at the same time and had no problem 

usually the "TOO_MANY_ACTIVE_STREAMS" happens when your limit with crunchyroll is reached - but i close the streams pretty fast maybe i have to add a delay of a couple of seconds 

you can also try to disable auto download and activate the downloads one by one

**Comment by petenun** [comment]
Successfully downloading one by one is what led me to the conclusion that there's nothing wrong with the files or download mechanism, and prompted me to look at the simultaneous downloads. When the big picture doesn't make sense, simplify to the essential parts. ☺

And good call; I'll be sure to check the Windows application logs next time around.

**Comment by petenun** [comment]
Problem is still happening sporadically. Here's info from the Application Event Logs. Hopefully this will help.

Application Error, Event ID 1000:

Faulting application name: CRD.exe, version: 1.5.27.0, time stamp: 0x65f90000
Faulting module name: KERNELBASE.dll, version: 10.0.17763.6189, time stamp: 0xd399e59c
Exception code: 0xe0434352
Fault offset: 0x0000000000041b39
Faulting process id: 0xa40
Faulting application start time: 0x01dafcc6d1e13fbb
Faulting application path: D:\Applications\Crunchy-Downloader\CRD.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 99478ed3-77e0-45cb-aab3-19a9a0535df6
Faulting package full name: 
Faulting package-relative application ID: 

------

.NET Runtime, Event ID 1026:

Application: CRD.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.HandleStreamErrorsAsync(ValueTuple`2 response, String mediaGuidId, String endpoint)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.FetchPlaybackData(String mediaId, String mediaGuidId, Boolean music)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadMediaList(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.ViewModels.DownloadItemModel.StartDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at CRD.Program.Main(String[] args)

**Comment by Elwador** [comment]
new version should at least fix the crash

**Comment by petenun** [comment]
Thank you. I'll give it a try and let you know in the next day or two when new episodes come out.
