### ISSUE TITLE
Crash due to missing base_frames directory

### ISSUE THREAD

**Issue by owenthewizard** [Crunchy-DL/Crunchy-Downloader#130]
```
Faulting application name: CRD.exe, version: 1.5.34.0, time stamp: 0x65f90000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4111, time stamp: 0x03c619d0
Exception code: 0xe0434352
Fault offset: 0x000000000005fabc
Faulting process id: 0x0x64A0
Faulting application start time: 0x0x1DB0DF0C5AC51AF
Faulting application path: C:\Crunchyroll-Downloader\CRD.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d8526615-bf44-4c00-984a-dd5106c988eb
Faulting package full name: 
Faulting package-relative application ID:
```

```
Application: CRD.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\me\AppData\Local\Temp\base_frames'.
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at CRD.Utils.Muxing.Merger.ProcessVideo(String baseVideoPath, String compareVideoPath)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.MuxStreams(List`1 data, CrunchyMuxOptions options, String filename)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.ViewModels.DownloadItemModel.StartDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at CRD.Program.Main(String[] args)
```

**Comment by Elwador** [comment]
comes from the syncing either you create the folder for now or disable the syncing
