### ISSUE TITLE
Otra vez sucede lo de los días de expiración

### ISSUE THREAD

**Issue by BattouKen** [Crunchy-DL/Crunchy-Downloader#135]
hace un tiempo pasó esto de que mi suscripción esta en los días de renovar y aun me deja ver los episodios de la web, pero me sale error de desencriptación en el downloader.

Translation: A while ago, this happened where my subscription was in the renewal days, and it still lets me watch the episodes on the website, but I get a decryption error in the downloader

![image](https://github.com/user-attachments/assets/9944910d-9f4c-4624-8327-ebebf3dd2ef9)

![image](https://github.com/user-attachments/assets/702255b5-4e4b-47a0-9f05-e969e99f3c28)

![image](https://github.com/user-attachments/assets/a8341d80-5c28-4327-81fd-c9af930b2971)

```
  "next_renewal_date": "2024-09-24T18:48:16-03:00",
  "currency_code": "",
  "is_active": false,
  "tax_included": false,
  "subscription_products": [],
  "third_party_subscription_products": [
    {
      "effective_date": "2024-08-20T17:43:25-04:00",
      "Source": "google-play",
      "source_reference": "npgdamoeabhcgkgljpbnfema.AO-J1Oz-JRf72jdjyMHk8sjchwzzG4bTSFFM26mbAszTkjXPtbCFPIcZpRmjeMf2l7lbYXvKGHoPf_w19Fd3cXAYH22b58HVMwWxL3UUCiw8j9HXJpa9AYU",
      "Sku": "crunchyroll.google.fanpack.monthly",
      "Tier": "fan_pack",
      "active_free_trial": false,
      "in_grace": true,
      "on_hold": false,
      "auto_renew": true,
      "expiration_date": "0001-01-01T00:00:00",
      "in_grace_expiration_date": "2024-09-24T18:48:16-03:00"
    }
  ],
  "nonrecurring_subscription_products": [],
  "funimation_subscriptions": []
}

```

![image](https://github.com/user-attachments/assets/2fd21ad6-389f-4a44-a322-a99897586d87)
![image](https://github.com/user-attachments/assets/97163d1a-743c-4ab0-854f-c1145b287796)

```
      "Sku": "crunchyroll.google.fanpack.monthly",
      "Tier": "fan_pack",
      "active_free_trial": false,
      "in_grace": true,
      "on_hold": false,
      "auto_renew": true,
      "expiration_date": "0001-01-01T00:00:00",
      "in_grace_expiration_date": "2024-09-24T18:48:16-03:00"
    }
  ],
  "nonrecurring_subscription_products": [],
  "funimation_subscriptions": []
}
Log mode enabled.
No proxy is being used.
Faild to download video - DL Stats: {"First":0,"Total":355,"Completed":190}
ProtoBuf.ProtoException: Invalid wire-type (6); this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354
   at ProtoBuf.ProtoReader.State.ThrowProtoException(String message) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 803
   at ProtoBuf.ProtoReader.State.ThrowWireTypeException() in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 797
   at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 987
   at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 979
   at ProtoBuf.ProtoReader.State.AppendExtensionDataImpl(IExtension extn) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 908
   at ProtoBuf.ProtoReader.State.AppendExtensionData(IExtensible instance) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 883
   at proto_2(State&, ClientIdentification)
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 1157
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer) in /_/src/protobuf-net.Core/ProtoReader.State.ReadMethods.cs:line 1137
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in /_/src/protobuf-net/Serializer.Deserialize.cs:line 20
   at CRD.Utils.DRM.Session..ctor(ContentDecryptionModule contentDecryptionModule, Byte[] pssh)
   at CRD.Utils.DRM.Widevine.getKeys(String pssh, String licenseServer, Dictionary`2 authData)
Failed to get encryption keys
```

**Comment by Elwador** [comment]
`Failed to get encryption keys`

has nothing to do with that that it says `Subscription maybe ended` in the profile tab

i don't know why it is so strange for you but with the date being `2024-09-24T18:48:16-03:00` your subscription clearly should have renewed by now

so there is probably nothing i can do about this problem
