### ISSUE TITLE
Instructions on how to build it?

### ISSUE THREAD

**Issue by supahfox** [Crunchy-DL/Crunchy-Downloader#138]
I've tried to download Avalonia but I can't get it to work. it says that I need to build it but it returns nothing

**Comment by supahfox** [comment]
Btw i'm using vscode with .net 8

**Comment by supahfox** [comment]
<img width="1800" alt="Captura de pantalla 2024-10-05 a la(s) 21 54 54" src="https://github.com/user-attachments/assets/9f3936af-27ae-416a-a1e4-8e791d279d28">
Managed to compile it to mac (kinda, as it doesn't recognize my ffmpeg path)

**Comment by Elwador** [comment]
well if it says its missing ffmpeg - you didn't put in the lib folder it doesn't look for a globally installed version

**Comment by supahfox** [comment]
Alright, fixed. I had to change path in Cfgmanager.cs

Now it returns this

`
Unhandled exception. System.IO.IOException: Read-only file system : '/fabuz'
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at CRD.Utils.Helpers.EnsureDirectoriesExist(String path) in /Users/fabuz/Crunchy-Downloader/CRD/Utils/Helpers.cs:line 101
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadVideo(VideoItem chosenVideoSegments, CrDownloadOptions options, String outFile, String tsFile, String tempTsFile, CrunchyEpMeta data, String fileDir) in /Users/fabuz/Crunchy-Downloader/CRD/Downloader/Crunchyroll/CrunchyrollManager.cs:line 1676
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadMediaList(CrunchyEpMeta data, CrDownloadOptions options) in /Users/fabuz/Crunchy-Downloader/CRD/Downloader/Crunchyroll/CrunchyrollManager.cs:line 1087
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options) in /Users/fabuz/Crunchy-Downloader/CRD/Downloader/Crunchyroll/CrunchyrollManager.cs:line 221
   at CRD.ViewModels.DownloadItemModel.StartDownload() in /Users/fabuz/Crunchy-Downloader/CRD/ViewModels/DownloadsPageViewModel.cs:line 186
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnPlatformThreadingInterfaceEventsVTable.Signaled(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at CRD.Program.Main(String[] args) in /Users/fabuz/Crunchy-Downloader/CRD/Program.cs:line 15
`

**Comment by Elwador** [comment]
as stated in the build guide, I do not provide support for issues when you build the project yourself. If you choose to compile it independently, any issues that arise are your responsibility. I only offer support for the prebuilt version available on GitHub

**Comment by Akczht** [comment]
it also says mkvmerge not found in system path, how t fix that on macos
