### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Wernouxe** [Crunchy-DL/Crunchy-Downloader#145]
When I try to download [Inayusha](https://www.crunchyroll.com/fr/series/G6DKW52DR/inuyasha) with JAP and FR audio and FR subtitles, CRD crashes after a while, I get no logs (even in the logfile).

**Comment by Elwador** [comment]
> https://github.com/Crunchy-DL/Crunchy-Downloader/issues/110

> Check the Windows Event Log (if the program crashes)
> 
> In the event of a program crash, please check the Windows Event Log for any related error messages (.NET runtime) and include that information in your report.

**Comment by Wernouxe** [comment]
```
Application: CRD.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wernauxe\Documents\dev\scripts\Crunchyroll-Downloader-v1.5.10\temp\compare_frames'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at CRD.Utils.Muxing.Merger.ProcessVideo(String baseVideoPath, String compareVideoPath)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.MuxStreams(List`1 data, CrunchyMuxOptions options, String filename)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.ViewModels.DownloadItemModel.StartDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at CRD.Program.Main(String[] args)
   ````

**Comment by Wernouxe** [comment]
@Elwador is this what you wanted?

**Comment by Elwador** [comment]
> @Elwador is this what you wanted?

yes
