### ISSUE TITLE
crashes when i try to download

### ISSUE THREAD

**Issue by aryaniiil** [Crunchy-DL/Crunchy-Downloader#184]
the download doesnt start and it crashed instantly while clicking the download button

**Comment by Elwador** [comment]
https://github.com/Crunchy-DL/Crunchy-Downloader/issues/110

**Comment by aryaniiil** [comment]
Log Name:      Application
Source:        .NET Runtime
Date:          21-12-2024 04:57:02
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-D4KMSAT
Description:
Application: CRD.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.<>c__DisplayClass29_0.<DownloadMediaList>b__16(VideoItem a)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadMediaList(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.ViewModels.DownloadItemModel.StartDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at CRD.Program.Main(String[] args)

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-12-20T23:27:02.0290569Z" />
    <EventRecordID>43204</EventRecordID>
    <Correlation />
    <Execution ProcessID="19184" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-D4KMSAT</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: CRD.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.&lt;&gt;c__DisplayClass29_0.&lt;DownloadMediaList&gt;b__16(VideoItem a)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadMediaList(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.ViewModels.DownloadItemModel.StartDownload()
   at System.Threading.Tasks.Task.&lt;&gt;c.&lt;ThrowAsync&gt;b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&amp; lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.StartCore(String[] args)
   at CRD.Program.Main(String[] args)
</Data>
  </EventData>
</Event>
i got this sorry forgot to add it

**Comment by Elwador** [comment]
what did you try to download?

**Comment by aryaniiil** [comment]
> what did you try to download?

i tried downloading one piece then didnt worked so tried blue lock

**Comment by Elwador** [comment]
go to the settings change something like the video quality - to something else and back to what you have it and try again

**Comment by aryaniiil** [comment]
> go to the settings change something like the video quality to something else and back to what you have it and try again

ye i changed somethings now it started working at first did the quality part but didn't worked later i changed the stream endpoint to android/phone and it worked! idk if its relevent or not but i got the device client id and the other file from android studio (i honestly didn't knew this existed before)
