### ISSUE TITLE
[Bug] Program unexpectedly exiting when selecting a series or viewing a series from URL

### ISSUE THREAD

**Issue by NobodyXIII** [Crunchy-DL/Crunchy-Downloader#52]
As per title, program closes unexpectedly whenever I select a series. I am logged into my account and have double checked that I installed the program as per the readme. I cannot get it to work. The log file is empty save for logging being enabled, and included is what I can glean from the event log in Windows.

[logfile.txt](https://github.com/user-attachments/files/16424989/logfile.txt)

Event log details:
There's one for the .NET runtime: 

Application: CRD.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: OVA1
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at CRD.Downloader.Crunchyroll.CrSeries.ListSeriesId(String id, String crLocale, Nullable`1 data)
   at CRD.ViewModels.AddDownloadPageViewModel.<OnSelectedSearchItemChanged>d__121.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at CRD.Program.Main(String[] args)

There's an event for the application as well:

Faulting application name: CRD.exe, version: 1.5.10.0, time stamp: 0x65f90000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3880, time stamp: 0xdb9989e8
Exception code: 0xe0434352
Fault offset: 0x000000000005fabc
Faulting process id: 0x0x3D18
Faulting application start time: 0x0x1DAE25E0793D332
Faulting application path: C:\Users\Dark_\Downloads\Crunchyroll-Downloader-v1.5.10\CRD.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 4c806810-379a-4be0-a5cb-4ac3f3c051ad
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Elwador** [comment]
i should be able to fix the bug with the .NET runtime log - but to test it what series are you trying to add?

**Comment by NobodyXIII** [comment]
So far just My Hero Academia. Would you like for me to experiment with some other series as well?

**Comment by Elwador** [comment]
new release that fixes the crash - [v1.5.11](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.11)

**Comment by NobodyXIII** [comment]
Thanks for the help and expedient response on top of that!
