### ISSUE TITLE
[Bug] Crash popup when opening if series deleted on sonarr

### ISSUE THREAD

**Issue by Nonobis** [Crunchy-DL/Crunchy-Downloader#53]
Hello,

Got an error with sonar, when opening the apps.

1. **Search Closed Issues**

Not found.

2. **Check the Wiki and Discussions**
Not found.

3. **Enable Log Mode and Check for Errors**

Log mode enabled.
Log mode enabled.
Sonarr GetSeries error 
Newtonsoft.Json.JsonSerializationException: Error converting value "deleted" to type 'CRD.Utils.SonarrStatus'. Path '[173].status', line 24246, position 23.
 ---> System.ArgumentException: Requested value 'deleted' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at CRD.Utils.Sonarr.SonarrClient.GetSeries()

4. **Check the Windows Event Log (if the program crashes)**

Not Necessary.

**Comment by Elwador** [comment]
for some reason the removed "Cardfight!! Vanguard overDress" from TVDB 😆 thats one reason why this error occurred the other i just forgot a enum value 
it's fixed in the new release [v1.5.12](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.5.12)

**Comment by Nonobis** [comment]
Thks :) I will try it today.

**Comment by Nonobis** [comment]
solved. Thanks
