### ISSUE TITLE
[Bug] Application randomly crashes

### ISSUE THREAD

**Issue by SaintXye** [Crunchy-DL/Crunchy-Downloader#92]
When trying to dl it would randomly crash
These were the .net crash reports (If I did this right) 

Application: CRD.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.ArgumentNullException.Throw(String paramName)
   at System.IO.Path.Combine(String path1, String path2)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.DownloadEpisode(CrunchyEpMeta data, CrDownloadOptions options)
   at CRD.ViewModels.DownloadItemModel.StartDownload()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at CRD.Program.Main(String[] args)

Application: CRD.exe
CoreCLR Version: 8.0.524.21615
.NET Version: 8.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\settings.yml' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at CRD.Utils.CfgManager.UpdateSettingsFromFile(CrDownloadOptions options)
   at CRD.Downloader.Crunchyroll.CrunchyrollManager.InitDownloadOptions()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at CRD.ViewModels.DownloadsPageViewModel..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at CRD.Views.MainWindow.NavView_SelectionChanged(Object sender, NavigationViewSelectionChangedEventArgs e)
   at FluentAvalonia.UI.Controls.NavigationView.ChangeSelection(Object prevItem, Object nextItem)
   at FluentAvalonia.UI.Controls.NavigationView.OnSelectedItemPropertyChanged(Object oldItem, Object newItem)
   at FluentAvalonia.UI.Controls.NavigationView.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority, Boolean isEffectiveValue)
   at Avalonia.AvaloniaObject.SetAndRaise[T](DirectPropertyBase`1 property, T& field, T value)
   at FluentAvalonia.UI.Controls.NavigationView.set_SelectedItem(Object value)
   at CRD.Views.MainWindow..ctor()
   at CRD.App.OnFrameworkInitializationCompleted()
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at CRD.Program.Main(String[] args)

**Comment by Elwador** [comment]
does it only crash if you try to download something?

**Comment by SaintXye** [comment]
I am not entirely sure what that means but I do have a config folder now
![Screenshot 2024-08-21 051459](https://github.com/user-attachments/assets/2742a565-ab56-4edd-9675-f7a806a81423)

**Comment by Elwador** [comment]
and does it still crash?

**Comment by SaintXye** [comment]
It stopped crashing but downloads will randomly stop

**Comment by Elwador** [comment]
have you tried the log mode for that?

**Comment by SaintXye** [comment]
I get the "Request to DRM Authentication failed" and have to retry some episodes 2-3 times for them to dl which isn't that big of a deal. if there is a fix that's awesome but I can deal with this

**Comment by SaintXye** [comment]
I was busy and was hard to test things before this so I apologize if I was making things more complicated than it needed to be.

I thought it stopped crashing but it just happened again so I deleted everything but the widevine folder and started over
I changed settings for: Folder locations, File naming, Dub Languages, and I enabled sync timings.

First launch the app crashed after I tried to add a anime to it but after I reopened it it seemed to work as intended
It will occasionally not add every episode of a show when I click "add missing" or "Download all" occasionally I will get a random "Request to DRM Authentication Failed" where I will need to retry the dl 2-3 times before it works again.

**Comment by Elwador** [comment]
are you using a vpn?

**Comment by SaintXye** [comment]
yes I am

**Comment by Elwador** [comment]
if it is not windscribe it is probably the cause

**Comment by SaintXye** [comment]
It is NordVPN

**Comment by Elwador** [comment]
yes NordVPN blocks some urls or something it gets really buggy if you use that

**Comment by SaintXye** [comment]
Is it fine to use without VPN?

**Comment by SaintXye** [comment]
Thank you I appreciate your patience and help :)

One more side note question: in the "Muxing Settings" there is an option for custom FFMpeg options. What would you suggest for smaller file sizes? I usually run them through handbrake but was wondering if I could do something similar using that.

**Comment by Elwador** [comment]
FFMpeg is only if you have selected the MP4 option else you would have to change the options for mkvmerge

but for example for ffmpeg you could set (examples not necessarily improvements for file size)
"-c:v libx264" - to change the video codec
"-c:a aac" - to change the audio codec 
"-b:v 2M -b:a 128k" - or you could change the bitrate
"-crf 23" - constatnt rate factor could be changed like this 

but i would suggest to look into the ffmpeg commands on how you could improve file size or keep running the files through handbreak
